### ISSUE TITLE
Incorrect day while search

### ISSUE THREAD

**Issue by joroMaser** [guytepper/better-rail#84]
When I click on TODAY  I see the leaving  time is tomorrow 
![Search](https://user-images.githubusercontent.com/14313895/154843736-78d18668-27b9-4d94-a1fa-b76c70663045.jpg)
![Tom](https://user-images.githubusercontent.com/14313895/154843738-86dde897-159e-4504-a2d7-ea5a5cf535e9.jpg)

**Comment by guytepper** [comment]
Hey, thanks for the report!

This probably happens because the app has been open since yesterday, so the time formatter compares the current date to yesterday. 

I thought it was resolved by https://github.com/guytepper/better-rail/blob/main/app/screens/planner/planner-screen.tsx#L169-L189, so need to take a look there once I have time :)

**Comment by joroMaser** [comment]
@guytepper 
Yes. The application has been open since yesterday.
